language: ruby
sudo: required
dist: trusty
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- rvm use --default $TRAVIS_RUBY_VERSION
- echo 'export PATH="$PATH:/home/travis/.rvm/bin"' | sudo tee -a /etc/profile
- echo 'source /home/travis/.rvm/scripts/rvm' | sudo tee -a /etc/profile
- bundle exec rake default
- bundle exec kitchen test
- sudo chown -R travis:travis /home/travis/.rvm
- gem build sensu-plugins-postfix.gemspec
- gem install sensu-plugins-postfix-*.gem
env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
deploy:
  provider: rubygems
  api_key:
    secure: LkxKFc6KYmwTfuwIhFWSktky5TiJMvI79+RpHaX3BUyEnqZMAVNxtmTXpWqqglXGjgEGeClYl1WMCXIamw2zeLlK6CEuBJXcVXs4O27UKkvfzVmiDYBITPtF02mTVCTYd5NNch67Rh5rT7wTN2hxWbiE2OFw6/WIF9hD2mr1484=
  gem: sensu-plugins-postfix
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3
    repo: sensu-plugins/sensu-plugins-postfix
